"""draft table

Revision ID: 1bbaa40f8b8c
Revises: 4cdc7e782318
Create Date: 2026-07-29 02:37:04.639910
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '1bbaa40f8b8c'
down_revision: str | None = '4cdc7e782318'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hook_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hook_version', sa.Integer(), nullable=False),
    sa.Column('structure_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('structure_version', sa.Integer(), nullable=False),
    sa.Column('visual_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visual_version', sa.Integer(), nullable=True),
    sa.Column('hook_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visual_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_image', sa.LargeBinary(), nullable=True),
    sa.Column('visual_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zernio_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_hook_family'), 'draft', ['hook_family'], unique=False)
    op.create_index(op.f('ix_draft_mode'), 'draft', ['mode'], unique=False)
    op.create_index(op.f('ix_draft_structure_family'), 'draft', ['structure_family'], unique=False)
    op.create_index(op.f('ix_draft_visual_family'), 'draft', ['visual_family'], unique=False)
    op.create_index(op.f('ix_draft_zernio_post_id'), 'draft', ['zernio_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_zernio_post_id'), table_name='draft')
    op.drop_index(op.f('ix_draft_visual_family'), table_name='draft')
    op.drop_index(op.f('ix_draft_structure_family'), table_name='draft')
    op.drop_index(op.f('ix_draft_mode'), table_name='draft')
    op.drop_index(op.f('ix_draft_hook_family'), table_name='draft')
    op.drop_table('draft')
    # ### end Alembic commands ###
