"""post local media path

Revision ID: 3ea8ff85c496
Revises: b3784bcd19d0
Create Date: 2026-07-29 02:01:35.724380
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = '3ea8ff85c496'
down_revision: str | None = 'b3784bcd19d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'post',
        sa.Column('local_media_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'local_media_path')
    # ### end Alembic commands ###
