"""metric snapshot table

Revision ID: 4281be495457
Revises: 1bbaa40f8b8c
Create Date: 2026-07-29 02:50:54.953148
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4281be495457'
down_revision: str | None = '1bbaa40f8b8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('engaged_actions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_metric_snapshot_captured_at'), 'metric_snapshot', ['captured_at'], unique=False
    )
    op.create_index(
        op.f('ix_metric_snapshot_post_id'), 'metric_snapshot', ['post_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_snapshot_post_id'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_captured_at'), table_name='metric_snapshot')
    op.drop_table('metric_snapshot')
    # ### end Alembic commands ###
