"""template table

Revision ID: 4cdc7e782318
Revises: 3ea8ff85c496
Create Date: 2026-07-29 02:06:39.523911
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '4cdc7e782318'
down_revision: str | None = '3ea8ff85c496'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('HOOK', 'STRUCTURE', 'VISUAL', name='templatekind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column(
        'status',
        sa.Enum('PROPOSED', 'APPROVED', 'RETIRED', name='templatestatus'),
        nullable=False,
    ),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_family_id'), 'template', ['family_id'], unique=False)
    op.create_index(op.f('ix_template_kind'), 'template', ['kind'], unique=False)
    op.create_index(op.f('ix_template_status'), 'template', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_status'), table_name='template')
    op.drop_index(op.f('ix_template_kind'), table_name='template')
    op.drop_index(op.f('ix_template_family_id'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
