"""draft zernio_media_url

Revision ID: 6910a95bf6be
Revises: e97db40b4755
Create Date: 2026-08-04 13:00:00.963206
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = '6910a95bf6be'
down_revision: str | None = 'e97db40b4755'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'draft',
        sa.Column('zernio_media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'zernio_media_url')
    # ### end Alembic commands ###
