"""post source

Revision ID: 959fc1ba1cc5
Revises: 4281be495457
Create Date: 2026-07-29 03:07:15.320125
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '959fc1ba1cc5'
down_revision: str | None = '4281be495457'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add_column does NOT create the PG enum type (create_table does, implicitly), and a
    # NOT NULL column on a populated table needs a default for the existing rows.
    postsource = postgresql.ENUM('ZERNIO', 'MANUAL', name='postsource')
    postsource.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'post',
        sa.Column('source', postsource, nullable=False, server_default='ZERNIO'),
    )
    op.create_index(op.f('ix_post_source'), 'post', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_source'), table_name='post')
    op.drop_column('post', 'source')
    postgresql.ENUM(name='postsource').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
