"""post table

Revision ID: b3784bcd19d0
Revises: c2756fd0ca1a
Create Date: 2026-07-29 01:56:14.912328
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'b3784bcd19d0'
down_revision: str | None = 'c2756fd0ca1a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zernio_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('late_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('platform_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('platform_post_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('follows', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('engaged_actions', sa.Integer(), nullable=False),
    sa.Column('metrics_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_engaged_actions'), 'post', ['engaged_actions'], unique=False)
    op.create_index(op.f('ix_post_platform'), 'post', ['platform'], unique=False)
    op.create_index(op.f('ix_post_published_at'), 'post', ['published_at'], unique=False)
    op.create_index(op.f('ix_post_zernio_id'), 'post', ['zernio_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_zernio_id'), table_name='post')
    op.drop_index(op.f('ix_post_published_at'), table_name='post')
    op.drop_index(op.f('ix_post_platform'), table_name='post')
    op.drop_index(op.f('ix_post_engaged_actions'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
