"""draft previous visual

Revision ID: e97db40b4755
Revises: c8d42ea1f5b3
Create Date: 2026-08-04 08:51:22.668780
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'e97db40b4755'
down_revision: str | None = 'c8d42ea1f5b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('previous_visual', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'previous_visual')
    # ### end Alembic commands ###
